apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
---
apiVersion: v1
kind: Secret
metadata:
  name: opstasks-secret
  namespace: demo-app
type: Opaque
stringData:
  DATABASE_USER: opstasks
  DATABASE_PASSWORD: opstasks
